# Generated by Django 5.0.6 on 2025-02-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
