# Generated by Django 5.0.6 on 2024-05-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_develop',
            field=models.BooleanField(default=False),
        ),
    ]
