# Generated by Django 5.0.6 on 2025-07-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_organization_alter_user_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bayanihan_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registrar',
            field=models.BooleanField(default=False),
        ),
    ]
