# Generated by Django 5.0.6 on 2025-02-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
