# Generated by Django 5.2.6 on 2025-10-10 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_peo_is_active_programoutcome_is_active_and_more'),
        ('bayanihan', '0002_initial'),
        ('syllabi', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('chair_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('chair_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('dean_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dean_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('dean_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bayanihan_group', models.ForeignKey(help_text='Bayanihan group associated with the syllabus.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bayanihan.bayanihangroup')),
                ('syllabus', models.ForeignKey(help_text='The syllabus this report is tracking.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='syllabi.syllabus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syll_deadline', models.DateTimeField(blank=True, null=True)),
                ('tos_midterm_deadline', models.DateTimeField(blank=True, null=True)),
                ('tos_final_deadline', models.DateTimeField(blank=True, null=True)),
                ('school_year', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('1ST', '1st Semester'), ('2ND', '2nd Semester'), ('SUMMER', 'Summer')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='academics.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('college', 'school_year', 'semester')},
            },
        ),
    ]
