# Generated by Django 5.2.6 on 2025-10-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deadline',
            unique_together=set(),
        ),
    ]
