# Generated by Django 5.2.6 on 2025-10-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_curriculum_program_alter_peo_program_and_more'),
        ('shared', '0002_alter_deadline_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='syll_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='deadline',
            name='tos_final_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='deadline',
            name='tos_midterm_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='deadline',
            unique_together={('college', 'school_year', 'semester')},
        ),
    ]
