# Generated by Django 5.2.6 on 2025-10-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [ 
        ('shared', '0003_deadline_syll_status_deadline_tos_final_status_and_more'),
    ]

    operations = [
    ]
