# Generated by Django 5.2.6 on 2025-11-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanihan', '0003_alter_bayanihangroup_unique_together_and_more'),
        ('shared', '0004_merge_20251024_1358'),
        ('tos', '0008_rename_effectivity_date_tos_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('chair_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('chair_returned_at', models.DateTimeField(blank=True, null=True)),
                ('chair_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bayanihan_group', models.ForeignKey(help_text='Bayanihan group associated with the TOS.', on_delete=django.db.models.deletion.CASCADE, related_name='tos_reports', to='bayanihan.bayanihangroup')),
                ('tos', models.ForeignKey(help_text='The TOS this report is tracking.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tos.tos')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
