# Generated by Django 5.2.6 on 2025-09-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CotComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SrfChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SRF Checklist Item',
                'verbose_name_plural': 'SRF Checklist Items',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('class_schedules', models.TextField()),
                ('building_room', models.CharField(max_length=255)),
                ('consultation_hours', models.TextField()),
                ('consultation_room', models.TextField()),
                ('course_description', models.TextField()),
                ('course_requirements', models.TextField(blank=True, null=True)),
                ('chair_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('chair_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('dean_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dean_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('dean_approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.PositiveIntegerField()),
                ('dean', models.JSONField(blank=True, null=True)),
                ('chair', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusCotCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusCourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_code', models.CharField(max_length=20)),
                ('co_description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusCourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_term', models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('PRE-FINALS', 'Pre-finals'), ('FINALS', 'Finals')], max_length=20)),
                ('row_no', models.PositiveIntegerField(blank=True, null=True)),
                ('allotted_hour', models.PositiveIntegerField()),
                ('allotted_time', models.TextField(blank=True, null=True)),
                ('intended_learning', models.TextField(blank=True, null=True)),
                ('topics', models.TextField()),
                ('suggested_readings', models.TextField(blank=True, null=True)),
                ('learning_activities', models.TextField(blank=True, null=True)),
                ('assessment_tools', models.TextField(blank=True, null=True)),
                ('grading_criteria', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusDeanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusReviewForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=255)),
                ('sem_year', models.CharField(max_length=50)),
                ('faculty', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('reviewed_by_snapshot', models.CharField(max_length=255)),
                ('action', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Syllabus Review Form',
                'verbose_name_plural': 'Syllabus Review Forms',
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllCoPo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_co_po_code', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
