# Generated by Django 5.2.6 on 2025-09-20 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('bayanihan', '0002_initial'),
        ('syllabi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='bayanihan_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='bayanihan.bayanihangroup'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.college'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.course'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.department'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='peos',
            field=models.ManyToManyField(blank=True, related_name='syllabi', to='academics.peo'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='program_outcomes',
            field=models.ManyToManyField(blank=True, related_name='syllabi', to='academics.programoutcome'),
        ),
        migrations.AddField(
            model_name='headercomment',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_comments', to='syllabi.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabuscourseoutcome',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='syllabi.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabuscotco',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotcos', to='syllabi.syllabuscourseoutcome'),
        ),
        migrations.AddField(
            model_name='cocomment',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='syllabi.syllabuscourseoutcome'),
        ),
        migrations.AddField(
            model_name='syllabuscourseoutline',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outlines', to='syllabi.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabuscotco',
            name='course_outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotcos', to='syllabi.syllabuscourseoutline'),
        ),
        migrations.AddField(
            model_name='cotcomment',
            name='course_outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='syllabi.syllabuscourseoutline'),
        ),
        migrations.AddField(
            model_name='syllabusdeanfeedback',
            name='syllabus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dean_feedback', to='syllabi.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabusdeanfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabusinstructor',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='syllabi.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabusinstructor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabusreviewform',
            name='syllabus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_form', to='syllabi.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabusreviewform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='srfchecklist',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='syllabi.syllabusreviewform'),
        ),
        migrations.AddField(
            model_name='syllcopo',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllcopos', to='syllabi.syllabuscourseoutcome'),
        ),
        migrations.AddField(
            model_name='syllcopo',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.programoutcome'),
        ),
        migrations.AddField(
            model_name='syllcopo',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllcopos', to='syllabi.syllabus'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabuscotco',
            unique_together={('course_outline', 'course_outcome')},
        ),
        migrations.AlterUniqueTogether(
            name='srfchecklist',
            unique_together={('review_form', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='syllcopo',
            unique_together={('course_outcome', 'program_outcome')},
        ),
    ]
