# Generated by Django 5.2.6 on 2025-10-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity_date', models.DateTimeField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='documentImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
