# Generated by Django 5.2.6 on 2025-10-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_curriculum_department_and_more'),
        ('syllabi', '0003_syllabitemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='department',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.program'),
        ),
    ]
