# Generated by Django 5.2.6 on 2025-10-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_curriculum_program_alter_peo_program_and_more'),
        ('syllabi', '0004_remove_syllabus_department_syllabus_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.program'),
        ),
    ]
