# Generated by Django 5.2.6 on 2025-10-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0005_alter_syllabus_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabitemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='syllabitemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syllabitemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='syllabitemplate',
            name='effectivity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
