# Generated by Django 5.2.6 on 2025-10-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0006_alter_syllabitemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotcomment',
            name='course_outline',
        ),
        migrations.RemoveField(
            model_name='cotcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='headercomment',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='headercomment',
            name='user',
        ),
        migrations.CreateModel(
            name='SyllabusComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('header_1', 'Header 1 - College Info'), ('header_2', 'Header 2 - Department Info'), ('header_3', 'Header 3 - Course Info'), ('section_1', 'Section 1 - Class Schedule / Rooms'), ('section_2', 'Section 2 - Pre-req / Co-req'), ('section_3', 'Section 3 - Instructor Details'), ('section_4', 'Section 4 - Consultation Details'), ('course_description', 'Course Description'), ('course_outcomes', 'Course Outcomes'), ('course_outline', 'Course Outline'), ('course_requirements', 'Course Requirements'), ('side_vision_mission', 'University Vision/Mission/Core Values'), ('side_peos', 'Program Educational Objectives (PEOs)'), ('side_pos', 'Program Outcomes (POs)')], help_text='Which section of the syllabus this comment refers to.', max_length=50)),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('syllabus', models.ForeignKey(help_text='The syllabus this comment is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='syllabi.syllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CoComment',
        ),
        migrations.DeleteModel(
            name='CotComment',
        ),
        migrations.DeleteModel(
            name='HeaderComment',
        ),
    ]
