# Generated by Django 5.2.6 on 2025-10-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0007_remove_cotcomment_course_outline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(default='FM-USTP-ACAD-12', max_length=50)),
                ('title', models.CharField(default='Syllabus Review Form', max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='syllabuscomment',
            name='section',
            field=models.CharField(choices=[('header_1', 'Header 1 - Department Info'), ('header_2', 'Header 2 - Course Info'), ('section_1', 'Section 1 - Class Schedule / Rooms'), ('section_2', 'Section 2 - Pre-req / Co-req'), ('section_3', 'Section 3 - Instructor Details'), ('section_4', 'Section 4 - Consultation Details'), ('course_description', 'Course Description'), ('course_outcomes', 'Course Outcomes'), ('course_outlines', 'Course Outlines'), ('course_requirements', 'Course Requirements'), ('side_vision_mission', 'University Vision/Mission/Core Values'), ('side_peos', 'Program Educational Objectives (PEOs)'), ('side_pos', 'Program Outcomes (POs)')], help_text='Which section of the syllabus this comment refers to.', max_length=50),
        ),
        migrations.CreateModel(
            name='ReviewFormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part', 'Part Header'), ('indicator', 'Indicator')], default='indicator', max_length=20)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='syllabi.reviewformtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('header', 'Header'), ('body', 'Body'), ('footer', 'Footer')], default='header', help_text='Where this field appears on the form layout.', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='syllabi.reviewformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SRFFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabi.reviewformfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='syllabi.syllabusreviewform')),
            ],
        ),
        migrations.CreateModel(
            name='SRFForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('reviewed_by_snapshot', models.CharField(max_length=255)),
                ('action', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabi.reviewformtemplate')),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='syllabi.syllabus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_reviewings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Syllabus Review Form',
                'verbose_name_plural': 'Syllabus Review Forms',
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SRFIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='syllabi.reviewformitem')),
                ('review_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='syllabi.syllabusreviewform')),
            ],
            options={
                'verbose_name': 'SRF Checklist Item',
                'verbose_name_plural': 'SRF Checklist Items',
                'ordering': ['item__order'],
                'unique_together': {('review_form', 'item')},
            },
        ),
    ]
