# Generated by Django 5.2.6 on 2025-11-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0008_reviewformtemplate_alter_syllabuscomment_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewformfield',
            options={'ordering': ['position', 'row', 'column', 'display_order']},
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='column',
            field=models.PositiveIntegerField(default=0, help_text='Column index within section.'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='height',
            field=models.FloatField(default=0, help_text='Height of field (in % or px).'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='row',
            field=models.PositiveIntegerField(default=0, help_text='Row index within section.'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='width',
            field=models.FloatField(default=0, help_text='Width of field (in % or px).'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='x',
            field=models.FloatField(default=0, help_text='Horizontal position (in % or px).'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='y',
            field=models.FloatField(default=0, help_text='Vertical position (in % or px).'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='z_index',
            field=models.IntegerField(default=0, help_text='Stack order for overlapping elements.'),
        ),
        migrations.AlterField(
            model_name='reviewformfield',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('body', 'Body'), ('footer', 'Footer')], default='header', help_text='Which section this field belongs to in the form layout.', max_length=20),
        ),
    ]
