# Generated by Django 5.2.6 on 2025-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0009_alter_reviewformfield_options_reviewformfield_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewformfield',
            name='span_full',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
