# Generated by Django 5.2.6 on 2025-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0010_reviewformfield_span_full'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewformtemplate',
            options={'ordering': ['-version'], 'verbose_name': 'Review Form Template', 'verbose_name_plural': 'Review Form Templates'},
        ),
        migrations.RenameField(
            model_name='srffieldvalue',
            old_name='submission',
            new_name='review_form',
        ),
        migrations.AlterField(
            model_name='reviewformfield',
            name='span_full',
            field=models.BooleanField(default=False),
        ),
    ]
