# Generated by Django 5.2.6 on 2025-11-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0011_alter_reviewformtemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srfform',
            old_name='form',
            new_name='form_template',
        ),
        migrations.AlterField(
            model_name='srfindicator',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='syllabi.syllabusreviewform'),
        ),
    ]
