# Generated by Django 5.2.6 on 2025-11-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0012_rename_form_srfform_form_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srffieldvalue',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='syllabi.srfform'),
        ),
        migrations.AlterField(
            model_name='srfindicator',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='syllabi.srfform'),
        ),
    ]
