# Generated by Django 5.2.6 on 2025-11-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0013_alter_srffieldvalue_review_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srfindicator',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='syllabi.srfform'),
        ),
    ]
