# Generated by Django 5.2.6 on 2025-11-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0014_alter_srfindicator_review_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srfindicator',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='syllabi.srfform'),
        ),
        migrations.CreateModel(
            name='SyllabusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('anchor_id', models.CharField(blank=True, help_text='Used in frontend for scroll/highlight linking.', max_length=100, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='syllabi.syllabitemplate')),
            ],
        ),
        migrations.AddField(
            model_name='reviewformitem',
            name='syllabus_section',
            field=models.ForeignKey(blank=True, help_text='Which Syllabus Template section this indicator corresponds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_indicators', to='syllabi.syllabussection'),
        ),
    ]
