# Generated by Django 5.2.6 on 2025-11-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0015_alter_srfindicator_review_form_syllabussection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabussection',
            name='order',
        ),
    ]
