# Generated by Django 5.2.6 on 2025-11-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0016_remove_syllabussection_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SyllabiTemplate',
            new_name='SyllabusTemplate',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='syllabi.syllabustemplate'),
        ),
    ]
