# Generated by Django 5.2.6 on 2025-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0017_rename_syllabitemplate_syllabustemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabustemplate',
            name='code_no',
            field=models.CharField(default='FM-USTP-ACAD-01', max_length=50),
        ),
        migrations.AddField(
            model_name='syllabustemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabustemplate',
            name='title',
            field=models.CharField(default='Syllabus', max_length=255),
        ),
    ]
