# Generated by Django 5.2.6 on 2025-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0018_syllabustemplate_code_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabussection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabussection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
