# Generated by Django 5.2.6 on 2025-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0019_syllabussection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabussection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='syllabussection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
