# Generated by Django 5.2.6 on 2025-11-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0020_alter_syllabussection_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabussection',
            old_name='template',
            new_name='syllabus_template',
        ),
    ]
