# Generated by Django 5.2.6 on 2025-11-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0021_rename_template_syllabussection_syllabus_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabusreviewform',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='syllabusreviewform',
            name='user',
        ),
        migrations.DeleteModel(
            name='SrfChecklist',
        ),
        migrations.DeleteModel(
            name='SyllabusReviewForm',
        ),
    ]
