# Generated by Django 5.2.6 on 2025-11-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0022_remove_syllabusreviewform_syllabus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srfform',
            name='syllabus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_form', to='syllabi.syllabus'),
        ),
    ]
