# Generated by Django 5.2.6 on 2025-11-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0023_alter_srfform_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewformfield',
            name='height',
        ),
        migrations.RemoveField(
            model_name='reviewformfield',
            name='width',
        ),
        migrations.RemoveField(
            model_name='reviewformfield',
            name='x',
        ),
        migrations.RemoveField(
            model_name='reviewformfield',
            name='y',
        ),
        migrations.RemoveField(
            model_name='reviewformfield',
            name='z_index',
        ),
    ]
