# Generated by Django 5.2.6 on 2025-11-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0024_remove_reviewformfield_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewformfield',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', help_text='Which section this field belongs to in the form layout.', max_length=20),
        ),
    ]
