# Generated by Django 5.2.6 on 2025-11-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0025_alter_reviewformfield_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='building_room',
            field=models.TextField(),
        ),
    ]
