# Generated by Django 5.2.6 on 2025-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0026_alter_syllabus_building_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_template',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='class_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='consultation_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='building_room',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='class_schedules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='consultation_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='consultation_room',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
