# Generated by Django 5.2.6 on 2025-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0027_remove_syllabus_syllabus_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srfform',
            old_name='effectivity_date',
            new_name='effective_date',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='effectivity_date',
            new_name='effective_date',
        ),
        migrations.RenameField(
            model_name='syllabustemplate',
            old_name='effectivity_date',
            new_name='effective_date',
        ),
        migrations.AlterField(
            model_name='syllabustemplate',
            name='code_no',
            field=models.CharField(default='FM-USTP-ACAD-01', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='syllabustemplate',
            name='title',
            field=models.CharField(default='Syllabus', editable=False, max_length=255),
        ),
    ]
