# Generated by Django 5.2.6 on 2025-11-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0028_rename_effectivity_date_srfform_effective_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabustemplate',
            old_name='version',
            new_name='revision_no',
        ),
    ]
