# Generated by Django 5.2.6 on 2025-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0029_rename_version_syllabustemplate_revision_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewformtemplate',
            options={'ordering': ['-revision_no'], 'verbose_name': 'Review Form Template', 'verbose_name_plural': 'Review Form Templates'},
        ),
        migrations.RenameField(
            model_name='reviewformtemplate',
            old_name='version',
            new_name='revision_no',
        ),
    ]
