# Generated by Django 5.2.6 on 2025-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0030_alter_reviewformtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewformfield',
            name='prefill_source',
            field=models.CharField(choices=[('none', 'None'), ('course_code', 'Course Code'), ('course_title', 'Course Title'), ('course_year_level', 'Course Year Level'), ('program_code', 'Program Code'), ('program_name', 'Program Name'), ('department_code', 'Department Code'), ('department_name', 'Department Name'), ('college_code', 'College Code'), ('college_name', 'College Name'), ('faculty', 'Faculty'), ('semester', 'Semester'), ('course_code_title', 'Course Code + Course Title'), ('semester_year', 'Semester + School Year')], default='none', help_text='If set, this field will automatically pull data from the Syllabus.', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewformfield',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=20),
        ),
    ]
