# Generated by Django 5.2.6 on 2025-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0031_reviewformfield_prefill_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewformitem',
            name='syllabus_section',
            field=models.CharField(blank=True, choices=[('format', 'Format'), ('header_1', 'Header 1'), ('header_2', 'Header 2'), ('section_1', 'Section 1'), ('section_2', 'Section 2'), ('section_3', 'Section 3'), ('section_4', 'Section 4'), ('side_section', 'Side Section'), ('course_description', 'Course Description'), ('course_outcomes', 'Course Outcomes'), ('course_outlines', 'Course Outlines'), ('course_requirements', 'Course Requirements')], help_text='Name of the syllabus section this indicator validates.', max_length=255, null=True),
        ),
    ]
