# Generated by Django 5.2.6 on 2025-11-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0032_alter_reviewformitem_syllabus_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='syllabi.syllabustemplate'),
        ),
        migrations.DeleteModel(
            name='SyllabusSection',
        ),
    ]
