# Generated by Django 5.2.6 on 2025-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0034_alter_reviewformfield_prefill_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewformtemplate',
            name='revision_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabustemplate',
            name='revision_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
