# Generated by Django 5.0.6 on 2026-04-07 08:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app_logos/')),
                ('logo_url', models.CharField(blank=True, help_text='External URL for logo image', max_length=500)),
                ('url', models.CharField(help_text='Route path for the app', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible_to_users', models.BooleanField(default=True, help_text='Show in user dashboard')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display apps')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
