# Generated by Django 5.2.6 on 2025-09-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('bayanihan', '0001_initial'),
        ('syllabi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TosComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_no', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TosRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True)),
                ('no_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('percent', models.PositiveIntegerField(blank=True, null=True)),
                ('no_items', models.PositiveIntegerField(blank=True, null=True)),
                ('col1_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('col2_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('col3_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('col4_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TosRowComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_no', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('PRE-FINALS', 'Pre-finals'), ('FINALS', 'Finals')], max_length=20)),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('total_items', models.PositiveIntegerField()),
                ('col1_percentage', models.PositiveIntegerField()),
                ('col2_percentage', models.PositiveIntegerField()),
                ('col3_percentage', models.PositiveIntegerField()),
                ('col4_percentage', models.PositiveIntegerField()),
                ('col1_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('col2_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('col3_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('col4_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('tos_cpys', models.TextField(blank=True, null=True)),
                ('chair', models.TextField(blank=True, null=True)),
                ('chair_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('chair_returned_at', models.DateTimeField(blank=True, null=True)),
                ('chair_approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending Review'), ('RETURNED', 'Returned'), ('REQUIRES_REVISION', 'Requires Revision'), ('REVISED', 'Revisions Applied'), ('APPROVED', 'Approved')], max_length=20, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bayanihan_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='bayanihan.bayanihangroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='academics.department')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='syllabi.syllabus')),
            ],
        ),
    ]
