# Generated by Django 5.2.6 on 2025-09-20 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toscomment',
            name='tos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tos.tos'),
        ),
        migrations.AddField(
            model_name='toscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tosrow',
            name='tos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tos.tos'),
        ),
        migrations.AddField(
            model_name='tosrowcomment',
            name='tos_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tos.tosrow'),
        ),
        migrations.AddField(
            model_name='tosrowcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
