# Generated by Django 5.2.6 on 2025-10-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tos',
            name='chair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tos',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tos',
            name='term',
            field=models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('SEMI-FINALS', 'Semi-finals'), ('FINALS', 'Finals')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tosrow',
            name='col1_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tosrow',
            name='col2_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tosrow',
            name='col3_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tosrow',
            name='col4_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tosrow',
            name='tos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_rows', to='tos.tos'),
        ),
    ]
