# Generated by Django 5.2.6 on 2025-10-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_curriculum_department_and_more'),
        ('tos', '0003_alter_tos_chair_alter_tos_status_alter_tos_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tos',
            name='department',
        ),
        migrations.AddField(
            model_name='tos',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='academics.program'),
        ),
    ]
