# Generated by Django 5.2.6 on 2025-10-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_curriculum_program_alter_peo_program_and_more'),
        ('tos', '0004_remove_tos_department_tos_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tos',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='academics.program'),
        ),
    ]
