# Generated by Django 5.2.6 on 2025-11-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0005_alter_tos_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toscomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='toscomment',
            name='col_no',
        ),
        migrations.AddField(
            model_name='toscomment',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toscomment',
            name='tos_row',
            field=models.ForeignKey(blank=True, help_text='The specific TOSRow this comment is associated with (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tos.tosrow'),
        ),
        migrations.AlterField(
            model_name='toscomment',
            name='tos',
            field=models.ForeignKey(help_text='The TOS this comment is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tos.tos'),
        ),
        migrations.DeleteModel(
            name='TosRowComment',
        ),
    ]
