# Generated by Django 5.2.6 on 2025-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0006_alter_toscomment_options_remove_toscomment_col_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(default='FM-USTP-ACAD-08', editable=False, max_length=50)),
                ('title', models.CharField(default='TOS', editable=False, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('revision_no', models.PositiveIntegerField(default=1, editable=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='documentImages/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
