# Generated by Django 5.2.6 on 2025-11-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0007_tostemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tos',
            old_name='effectivity_date',
            new_name='effective_date',
        ),
    ]
