# Generated by Django 5.2.6 on 2025-11-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0008_rename_effectivity_date_tos_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tos',
            name='tos_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_records', to='tos.tostemplate'),
        ),
    ]
