# Generated by Django 5.2.6 on 2025-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0009_tos_tos_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tostemplate',
            name='revision_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
