# Generated by Django 5.2.6 on 2025-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course', 'New Course'), ('group', 'Bayanihan Group'), ('role_assignment', 'Role Assignment')], max_length=50),
        ),
    ]
