# Generated by Django 5.2.6 on 2025-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course', 'New Course'), ('group', 'Bayanihan Group'), ('role_assignment', 'Role Assignment'), ('syllabus_review', 'Syllabus Needs Review'), ('syllabus_approval', 'Syllabus Needs Approval'), ('syllabus_approved', 'Syllabus Approved')], max_length=50),
        ),
    ]
