# Generated by Django 5.2.6 on 2025-10-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course', 'New Course'), ('group', 'Bayanihan Group'), ('role_assignment', 'Role Assignment'), ('syllabus_review', 'Syllabus Needs Review'), ('syllabus_approval', 'Syllabus Needs Approval'), ('syllabus_approved', 'Syllabus Approved'), ('syllabus_returned', 'Syllabus Returned'), ('syllabus_revision', 'Syllabus Revision'), ('tos_approval', 'TOS Needs Approval'), ('tos_approved', 'TOS Approved')], max_length=50),
        ),
    ]
