# Generated by Django 5.2.6 on 2025-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course', 'New Course'), ('group', 'Bayanihan Group'), ('role_assignment', 'Role Assignment'), ('syllabus_review', 'Syllabus Needs Review'), ('syllabus_approval', 'Syllabus Needs Approval'), ('syllabus_approved', 'Syllabus Approved'), ('syllabus_returned', 'Syllabus Returned'), ('syllabus_revision', 'Syllabus Revision'), ('tos_approval', 'TOS Needs Approval'), ('tos_approved', 'TOS Approved'), ('tos_review', 'TOS Needs Chair Review'), ('tos_returned', 'TOS Returned by Chair'), ('tos_approved_by_chair', 'TOS Approved by Chair'), ('tos_info', 'TOS Update Information')], max_length=50),
        ),
    ]
