# Generated by Django 5.2.6 on 2025-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='domain',
            field=models.CharField(blank=True, choices=[('syllabus', 'Syllabus'), ('tos', 'Table of Specifications'), ('memo', 'Memo'), ('group', 'Bayanihan Group'), ('role', 'Role Assignment'), ('deadline', 'Deadline'), ('system', 'System Message')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, help_text='Role of the user that should receive this notification', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('syllabus_review', 'Syllabus Needs Review'), ('syllabus_approval', 'Syllabus Needs Approval'), ('syllabus_returned', 'Syllabus Returned'), ('syllabus_approved', 'Syllabus Approved'), ('tos_review', 'TOS Needs Review'), ('tos_returned', 'TOS Returned'), ('tos_approved', 'TOS Approved'), ('role_assigned', 'New Role Assigned'), ('group_assignment', 'Bayanihan Group Assignment'), ('memo_new', 'New Memo'), ('deadline_reminder', 'Deadline Reminder')], max_length=50, null=True),
        ),
    ]
