# Generated by Django 5.2.6 on 2025-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_domain_notification_target_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('syllabus_review', 'Syllabus Needs Review'), ('syllabus_approval', 'Syllabus Needs Approval'), ('syllabus_returned', 'Syllabus Returned'), ('syllabus_approved', 'Syllabus Approved'), ('tos_review', 'TOS Needs Review'), ('tos_returned', 'TOS Returned'), ('tos_approved', 'TOS Approved'), ('role_assigned', 'New Role Assigned'), ('group_assignment', 'Bayanihan Group Assignment'), ('course_new', 'New Course'), ('memo_new', 'New Memo'), ('deadline_reminder', 'Deadline Reminder')], max_length=50, null=True),
        ),
    ]
