"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-tempkey")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["sea-lion-app-9h2ja.ondigitalocean.app"]

# Application definition
AUTH_USER_MODEL = "users.User"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders", 
    "rest_framework",
    'auditlog',
    'users',
    'academics.apps.AcademicsConfig',
    "bayanihan",
    'syllabi.apps.SyllabiConfig',
    'tos.apps.TosConfig', 
    'shared',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    'notifications.apps.NotificationsConfig',
    "storages",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'academics' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,  # keep connections alive for better performance
        ssl_require=False   # enforces SSL
    )
}

# Optional: fallback to SQLite for local dev if DATABASE_URL is missing
if not DATABASES["default"]:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }

# MySQL-specific settings
if DATABASES["default"].get("ENGINE") == "django.db.backends.mysql":
    DATABASES["default"]["OPTIONS"] = {
        "ssl_mode": "REQUIRED"  # enforce SSL correctly for MySQL
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# React Frontend Connection
# --------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ), 
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "BLACKLIST_AFTER_ROTATION": True,
}

CORS_ALLOWED_ORIGINS = [ 
    "http://localhost:5173",  # Syllabease2.0 frontend
    "http://localhost:3000",  # CITC Portal frontend
    "http://localhost:8000",  # CITC Portal backend
    "http://127.0.0.1:5173",  # Syllabease2.0 localhost
    "http://127.0.0.1:3000",  # CITC Portal localhost (frontend)
    "http://127.0.0.1:8000",  # CITC Portal localhost (backend)
    "https://syllabease2-0-deployment.vercel.app"
]

CORS_ALLOW_ALL_ORIGINS = False  

# CORS_ALLOW_HEADERS = [
#     "authorization",
#     "content-type",
#     "accept",
#     "origin",
#     "user-agent",
#     "dnt",
#     "cache-control",
#     "x-requested-with",
# ]
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

PASSWORD_RESET_TIMEOUT = 3600  # 1 hour in seconds

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# DigitalOcean Spaces Buckets
# AWS_ACCESS_KEY_ID = os.getenv("DO_SPACES_KEY")
# AWS_SECRET_ACCESS_KEY = os.getenv("DO_SPACES_SECRET")

# AWS_STORAGE_BUCKET_NAME = "syllabease-bucket"
# AWS_S3_REGION_NAME = "sgp1"

# AWS_S3_ENDPOINT_URL = "https://sgp1.digitaloceanspaces.com"
# AWS_S3_CUSTOM_DOMAIN = f"https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com"

# AWS_DEFAULT_ACL = "public-read"
# AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}

# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage-"

AWS_QUERYSTRING_AUTH = True # disable signed URLs

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": os.getenv("DO_SPACES_KEY"),
            "secret_key": os.getenv("DO_SPACES_SECRET"),
            "bucket_name": "syllabease-bucket",
            "region_name": "sgp1",
            "endpoint_url": "https://sgp1.digitaloceanspaces.com",
            "default_acl": "public-read",
            "object_parameters": {"CacheControl": "max-age=86400"},
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# -----------------------------
# Security headers
# -----------------------------
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = True
X_FRAME_OPTIONS = 'DENY'
# APPEND_SLASH = False

CSRF_TRUSTED_ORIGINS = [
    "https://sea-lion-app-9h2ja.ondigitalocean.app",
    "https://syllabease2-0-deployment.vercel.app",
]

# -----------------------------
# Logging (optional)
# -----------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "WARNING"},
}