# Generated by Django 5.2.6 on 2025-09-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=50, unique=True)),
                ('college_description', models.CharField(max_length=255)),
                ('college_status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_code', models.CharField(max_length=50, unique=True)),
                ('effectivity', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='memos/')),
                ('date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peo_code', models.CharField(max_length=50)),
                ('peo_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_letter', models.CharField(max_length=10)),
                ('po_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_unit_lec', models.PositiveSmallIntegerField(default=0)),
                ('course_unit_lab', models.PositiveSmallIntegerField(default=0)),
                ('course_credit_unit', models.PositiveSmallIntegerField(default=0)),
                ('course_hrs_lec', models.PositiveSmallIntegerField(default=0)),
                ('course_hrs_lab', models.PositiveSmallIntegerField(default=0)),
                ('course_pre_req', models.CharField(blank=True, max_length=255)),
                ('course_co_req', models.CharField(blank=True, max_length=255)),
                ('course_year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], max_length=2)),
                ('course_semester', models.CharField(choices=[('1ST', '1st Semester'), ('2ND', '2nd Semester'), ('SUMMER', 'Summer')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=50, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=255)),
                ('department_status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academics.college')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.department'),
        ),
    ]
