# Generated by Django 5.2.6 on 2025-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(choices=[('1ST', '1st Semester'), ('2ND', '2nd Semester'), ('MID_YEAR', 'Mid Year'), ('SUMMER', 'Summer')], max_length=10),
        ),
    ]
