# Generated by Django 5.2.6 on 2025-10-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_peo_is_active_programoutcome_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('college_code',), name='unique_college_code'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('college_description',), name='unique_college_description'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('curr_code',), name='unique_curr_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('department_code',), name='unique_department_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('department_name',), name='unique_department_name'),
        ),
    ]
