# Generated by Django 5.2.6 on 2025-10-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_college_unique_college_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='college',
            name='unique_college_code',
        ),
        migrations.RemoveConstraint(
            model_name='college',
            name='unique_college_description',
        ),
        migrations.RemoveConstraint(
            model_name='curriculum',
            name='unique_curr_code',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_code',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_name',
        ),
    ]
