# Generated by Django 5.2.6 on 2025-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curr_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=50),
        ),
    ]
