# Generated by Django 5.2.6 on 2025-10-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_college_college_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='program_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='peo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='programoutcome',
            name='department',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=255)),
                ('program_status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.department')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.program'),
        ),
        migrations.AddField(
            model_name='peo',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peos', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='academics.program'),
        ),
    ]
