# Generated by Django 5.2.6 on 2025-10-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_curriculum_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='peo',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peos', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='programoutcome',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='academics.program'),
        ),
    ]
