# Generated by Django 4.2.10 on 2025-11-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_curriculum_program_alter_peo_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='from_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='series_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='to_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
