# Generated by Django 4.2.10 on 2025-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_memo_bg_color_memo_from_field_memo_memo_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='rows',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
