# Generated by Django 5.2.6 on 2025-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_memo_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
