# Generated by Django 5.2.6 on 2025-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_reset_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
