# Generated by Django 5.2.6 on 2025-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
