# Generated by Django 5.0.6 on 2025-02-11 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.class'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.college'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.department'),
        ),
        migrations.AddField(
            model_name='class',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.schoolyear'),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.section'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.status'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.department'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.yearlevel'),
        ),
        migrations.AddField(
            model_name='class',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.yearlevel'),
        ),
    ]
