# Generated by Django 5.0.6 on 2024-12-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_subject_department_subject_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
