# Generated by Django 5.0.6 on 2025-02-13 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='endYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='startYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='tblYearLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.yearlevel'),
        ),
    ]
