# Generated by Django 5.0.6 on 2025-02-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_schoolyear_endyear_schoolyear_startyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
