# Generated by Django 5.0.6 on 2025-03-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_department_college_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
