# Generated by Django 5.0.6 on 2025-04-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_department_college'),
        ('lms', '0007_post'),
    ]

    operations = [
    ]
