# Generated by Django 5.0.6 on 2025-06-27 11:00

import app.lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Midyear', 'Midyear')], default='1st Semester', max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.lms.models.get_document_upload_path),
        ),
    ]
