# Generated by Django 5.0.6 on 2025-06-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_schoolyear_semester_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
