# Generated by Django 5.0.6 on 2025-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons', to='lms.lesson'),
        ),
    ]
