# Generated by Django 5.0.6 on 2025-07-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_class_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='lessons',
        ),
    ]
