# Generated by Django 5.0.6 on 2025-02-11 02:31

import app.unieventify.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventCategoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTypeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setupName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblstudentOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentOrgType', models.CharField(max_length=255)),
                ('studentOrgName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tblVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetinglink', models.TextField(blank=True, null=True)),
                ('eventName', models.TextField()),
                ('eventDescription', models.TextField()),
                ('startDateTime', models.DateTimeField(null=True)),
                ('endDateTime', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('approveDocuments', models.FileField(blank=True, null=True, upload_to=app.unieventify.models.get_document_upload_path)),
                ('images', models.ImageField(blank=True, null=True, upload_to=app.unieventify.models.get_image_upload_path)),
                ('isAnnouncement', models.BooleanField(null=True)),
                ('isAprrovedByDean', models.BooleanField(null=True)),
                ('isAprrovedByChairman', models.BooleanField(null=True)),
                ('majorEvent', models.BooleanField(null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('recurrence_days', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_createdby', to=settings.AUTH_USER_MODEL)),
                ('department', models.ManyToManyField(blank=True, null=True, to='lms.department')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='event_participants', to=settings.AUTH_USER_MODEL)),
                ('eventCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tbleventcategory')),
                ('eventType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tbleventtype')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tblsetup')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tblstatus')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tblvenue')),
            ],
        ),
        migrations.CreateModel(
            name='tblEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='unieventify.tblevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tblEventRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tblevent')),
            ],
        ),
        migrations.CreateModel(
            name='tblSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('schoolYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='tblEventSchoolYearAndSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(blank=True, to='unieventify.tblevent')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unieventify.tblsemester')),
            ],
        ),
    ]
