# Generated by Django 5.0.6 on 2025-02-18 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_status_name'),
        ('unieventify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblevent',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.status'),
        ),
        migrations.DeleteModel(
            name='tblStatus',
        ),
    ]
