# Generated by Django 5.2.6 on 2025-09-20 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bayanihan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bayanihangroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayanihan_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bayanihangroup',
            unique_together={('school_year', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='bayanihangroupuser',
            unique_together={('user', 'group', 'role')},
        ),
    ]
