# Generated by Django 5.2.6 on 2025-10-17 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_college_college_code_and_more'),
        ('bayanihan', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bayanihangroup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bayanihangroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bayanihan_groups', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='bayanihangroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bayanihan_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
